### ISSUE TITLE
fitparser-0.4.2/src/de/parser.rs panics with 'attempt to add with overflow'

### ISSUE THREAD

**Issue by evensolberg** [stadelmanma/fitparse-rs#10]
Trying to deserialize the attached file panics with an `'attempt to add with overflow'` message at `fitparser-0.4.2/src/de/parser.rs:551:17`. All other files I have worked fine, and [FitFileExplorer](https://apps.apple.com/us/app/fit-file-explorer/id1244431640?mt=12) ([source code](https://github.com/roznet/connectstats)) is able to read it.

The offending file can be found here: <https://www.dropbox.com/s/wbetd5llug0v4yt/add_with_overflow.fit?dl=0>

**Comment by stadelmanma** [comment]
@evensolberg So it looks like the issue is an array field that has the type Uint16 which I'm not sure how that is supposed to actually work since in theory you can only fit 127 uint16 values in 255 bytes. I noticed that the FitDecodeExample.jar and FitTestTool.jar included in the SDK fails on the file. This project can decode it, https://github.com/polyvertex/fitdecode, but casts it to a Byte field which doesn't seem right unless my FIT type detection has an edge case bug.

```
[Local message #3, global message #11]
        FieldDefinition {
            field_definition_number: 55,
            size: 255,
            base_type: UInt16,
        },
```

**Comment by stadelmanma** [comment]
Also I'm seeing fields that have a size of zero, it doesn't sound like this is explicitly prohibited since the SDK just says a "multiple of the base type" and I can't find any "field size > 0" assertions in the SDK but it seems odd to me.

I'm not 100% convinced this a truly valid FIT file and might just be something that the tool you mentioned parses because it's more forgiving than my parser. I'm going to keep digging some though.

I think one thing this has highlighted is that I might want to handle invalid fields with a little more grace. The SDK mentions this behavior "When the decoder encounters unknown or invalid data, it will assign an invalid value according to the designated base type." So maybe when the field size isn't an integer multiple of the type size I'll swallow the remaining bytes and push an invalid value in. In the very least I need to ensure a panic isn't thrown.

**Comment by evensolberg** [comment]
I did some more digging here too, and the files from the day before and from less than a week later are fine. I suspect there may well be a bug in the software that produced the file. I'm not thrilled with Wahoo for not including proper software version information in the file. They upgraded very frequently there for a while, so this may have been a bad version from their side or some corner case combination of values going into the file.

That being said, making your parser more robust is never a bad idea either, and it would be much appreciated. 😄

**Comment by stadelmanma** [comment]
@evensolberg sorry for the silence, I've not been able to get back around to this in some time but I have cut a new release that addresses the raw panic you were seeing due to field length as well as some extra handling when the field size doesn't align with an integer multiple of the file size. The FIT SDK can't parse the file and nor could another opens source parser I tried so I think I'm going to hang it up for now but thank you again for submitting this file, I was able to learn alot!

**Comment by evensolberg** [comment]
Thank you! I'm very much looking forward to trying this new version and also digging into the code to see what has changed and learn lots too. 😊
