### ISSUE TITLE
Consider using Arc instead of Rc for wrapping `FitDefinitionMessage`

### ISSUE THREAD

**Issue by danielalvsaaker** [stadelmanma/fitparse-rs#11]
Error is not Send because Rc shows up in `FitObject`, making it very difficult to deal with error handling across threads.
Using Arc instead would make the library more  ergonomic to use in contexts requiring Send.

**Comment by stadelmanma** [comment]
@danielalvsaaker  I'm glad you didn't see any performance degradation in the change. I believe the reason I used Rc instead of Arc is that parsing of data has to be a serial process. Since the context of the data at any, single part of the file is dependent on what has come before it and I couldn't see a way that you could parse a single file in a multi-threaded environment.

I can see parallelizing over the files themselves e.g. 10 files processed in parallel by 10 processes/threads. Do we need to allow Arc's to support mutiple processes over multiple files? Or am I totally missing the need for Arc's because of my lack of understanding how threads ago here?

**Comment by danielalvsaaker** [comment]
So my use case is parallelizing over multiple files and avoid blocking the async context. I hand off parsing to a dedicated thread pool and return the Result<T, Error> back to the main thread so I can handle the potential error. 

The reason for Arc is unrelated to the actual parsing, but simply so Error can be passed around ergonomically afterwards, as stated. Of course, this is just a proposal and there are potentially other ways to solve this.

**Comment by stadelmanma** [comment]
@danielalvsaaker sounds good. I think I'm on board, any the other sub-types returned in a `FitObject` are fine as they stand since their composition allows them to automatically get `Send` derived?.

**Comment by danielalvsaaker** [comment]
@stadelmanma That's exactly right.

**Comment by stadelmanma** [comment]
Merged the PR and cut release 0.5.0 which also includes the most recent SDK profile
