### ISSUE TITLE
Workout Step "custom_target_value_low"/"custom_target_value_high" unknown variant but work with fitfileviewer.com

### ISSUE THREAD

**Issue by zakstucke** [stadelmanma/fitparse-rs#19]
Attached example failing fit.

When using [https://www.fitfileviewer.com/](https://www.fitfileviewer.com), Workout Step "custom_target_value_low"/"custom_target_value_high" show correctly, however in the output of `from_bytes_with_options` these records come such as:
```
    {
        "kind": "workout_step",
        "fields": [
            { "name": "wkt_step_name", "number": 0, "value": "", "units": "" },
            { "name": "duration_type", "number": 1, "value": "time", "units": "" },
            { "name": "duration_time", "number": 2, "value": 240.0, "units": "s" },
            { "name": "target_type", "number": 3, "value": "heart_rate", "units": "" },
            { "name": "target_hr_zone", "number": 4, "value": 0, "units": "" },
            {
                "name": "custom_target_heart_rate_low",
                "number": 5,
                "value": "unknown_variant_84",
                "units": "% or bpm"
            },
            {
                "name": "custom_target_heart_rate_high",
                "number": 6,
                "value": "unknown_variant_125",
                "units": "% or bpm"
            },
            { "name": "intensity", "number": 7, "value": "active", "units": "" },
            { "name": "notes", "number": 8, "value": "", "units": "" },
            { "name": "message_index", "number": 254, "value": "unknown_variant_0", "units": "" }
        ]
    },
```

I checked the header:
```
Header(FitFileHeader { header_size: 14, protocol_ver_enc: 2.0, profile_ver_enc: 21.25, data_size: 212344, crc: Some(6530) })
```

and thought it might be something to do with an older fit SDK profile being used to encode the fit, so tried with 21.40.00 (the oldest I could download) and the issue still persists.

Example fit with this issue attached below:

[failing_activity.zip](https://github.com/stadelmanma/fitparse-rs/files/9938819/failing_activity.zip)

On Fit file viewer website:
![image](https://user-images.githubusercontent.com/44890343/199990504-c471e1c3-b13b-4ae6-93a8-70679c602dd6.png)

Thanks!

**Comment by stadelmanma** [comment]
@zakstucke I’m a bit confused. Is the issue that the custom_target_heart_rate fields are saying “unknown_variant_##”? Instead of just the number?

**Comment by stadelmanma** [comment]
Did some digging into the profile, I think this is actually a feature request and not a bug per se. So the profile generation code picks it up like an enum field since it has a variant but the variant is actually just a sentinel value for when the meaning of the field changes from a percent to an actual value. It's a challenging thing to support without hard coding special cases into the profile generation code which given the size of the FIT profile I take pains to avoid. This happens in a few places, the "quick fix" might be to just swap out "UnknownVariant(value)" For an actual "Value(value)" variant in the field type. Unfortunately that obscures the true nature of a field like WorkoutHr where below 100 it;s actually a percentage and above 100 it's an actual BPM.
    
![Screenshot from 2022-11-05 21-42-58](https://user-images.githubusercontent.com/16710141/200150204-65663e4b-e545-4430-a6ae-5965e09122bb.png)

**Comment by zakstucke** [comment]
@stadelmanma this makes sense. So it looks like the lib does apply the bpm offset, it just prepends unknown_variant given it could be a % or a bpm, depending on whether the value (pre bpm offset correction) was greater than 100 (bpm) or not (%).

I do think this is closer to a bug than a feature request, it's something that's supported by other popular fit parsing libraries. I just checked python-fitparse where it also parses correctly to the following with the same example: 
```
    {
        "type": "workout_step",
        "data": {
            "custom_target_heart_rate_high": 125,
            "custom_target_heart_rate_low": 84,
            "duration_time": 240.0,
            "duration_type": "time",
            "equipment": null,
            "exercise_category": null,
            "exercise_name": null,
            "exercise_weight": null,
            "intensity": "active",
            "message_index": 0,
            "notes": null,
            "target_hr_zone": 0,
            "target_type": "heart_rate",
            "weight_display_unit": null,
            "wkt_step_name": null
        }
    }
```

It's problematic as it makes workout parsing (when the workout uses heart rate, power seems to be fine) obsolete with this library. 

I think this library has the potential to be the go-to fit parser for maximum speed, so it's essential it can extract important information like this without having to resort to end-user hacks, especially when as you say this actually occurs in quite a few places, which must all currently be defaulting to "unknown_variant"

Agree that hardcoded manual fixes would become unmanageable and tedious. Maybe taking advantage of the _offset fields could be a general solution. Watts and hr in the example you provided from the profile use percentage below the offset and raw values above, this could be used to specify the actual units in the "units" field?

**Comment by stadelmanma** [comment]
@zakstucke FIT profiles are customizable as well which is the other hang up on hard coding fixes. The two other parsers you mentioned spit out the literal value and don’t try to conform it to what the profile comments specify. So you still get 84 and 125 instead of something like 160-225. (160 = .84(220-AGE) and 125+100). 


One solution is probably a combination of seeing if there’s a reliable-ish naming convention and doing some sniffing for keywords in the comments field but that might be problematic if someone generates the parsing code with a custom profile that doesn’t match conventions.

I think the best option might be to do what those other libs do and just return the literal value instead of calling it “UnknownVariant##” when the field type in the profile isn’t explicitly an enum.

**Comment by stadelmanma** [comment]
@zakstucke I pushed some initial changes to this branch, https://github.com/stadelmanma/fitparse-rs/tree/improve-handling-of-non-enum-field-types but I've got some code in the decoder than coerces enum variants to strings so we went from `"unknown_variant_125"` to `"125"` which is an improvement but not quite to the mark. I'll need some more time and fresher eyes to work over the implications of dropping that coercion code.

**Comment by zakstucke** [comment]
@stadelmanma this sounds like the right approach. From the looks of it, it doesn't look like this fit file conforms to the comments anyway. If you look at the workout as a whole, the raw values make much more sense than values that conform to the comments in the profile. 

E.g. the first step of the workout, which in this case is clearly a warmup, the raw values are 84 to 125, this makes much more sense as a warmup heart rate range than 160-225, which are very high hr values, the latter of which is greater than 100% max HR, as would be if in line with the comments. 

In my opinion, the coercion code should go, the values should be parsed to their numerical type, and leave the interpretation of the values to the user. As you said, and exemplified by my above example, the comments cannot be relied upon given customisable profiles and fit implementations.

PS, this file came directly from garmin, so it doesn't look as if they follow their own specification if the above observations are accurate!

**Comment by zakstucke** [comment]
@stadelmanma another part of this is the field name looks like it should be `custom_target_value_low`/`custom_target_value_high` rather than `custom_target_heart_rate_low`/`custom_target_heart_rate_high`. 

This is what seems to occur for power based fields currently, see: 
[power_activity_fit.zip](https://github.com/stadelmanma/fitparse-rs/files/9951761/power_activity_fit.zip).

The example I originally gave on fitfileviewer.com also does this name standardization to these generic field names rather than the HR specific name.

This makes sense and looks like what this lib is already meant to be doing based on this power example. 

What do you think?

**Comment by zakstucke** [comment]
@stadelmanma any updates on this? Thanks :)

**Comment by stadelmanma** [comment]
@zakstucke sorry, I haven’t had a chance to work on this more yet but I haven’t forgotten. For a “csv” style display the name transform makes sense but when dumping to a mapping you could get key collisions, looks like the python lib keeps the longer name as well.

**Comment by stadelmanma** [comment]
Hey @zakstucke I've pushed some more changes but I'm not quite done yet, to fully support this use case I added a new decode option variant `DecodeOption::ReturnNumericEnumValues`. I think in some cases the string name of the enum variant might be more useful (e.g. manufacturer and device) to the average user but that isn't true for all enum FieldDataTypes. However, passing that decode option into the `from_*` methods will give you the numeric value for *ALL* enum types.

I think my new desired default behavior would be to return the string name of named variants or the numeric value for unknown variants. It won't always be perfect since not all of the FIT data types that present as enums are really meant to be treated as such, and some FIT files don't follow the publicly available profile anyways..

Let me know your thoughts after testing!

**Comment by zakstucke** [comment]
@stadelmanma I've run the same example fit file with 0.5.1 and the branch `improve-handling-of-non-enum-field-types`, run a diff and the changes in output make sense!

1. It looks like they're being parsed to strings rather than integers, I think the latter would make more sense? 
2. The issue of `custom_target_value_low`/`custom_target_value_high` rather than `custom_target_heart_rate_low`/`custom_target_heart_rate_high` mentioned in above [comment](https://github.com/stadelmanma/fitparse-rs/issues/19#issuecomment-1305579173) still persists. 
  There's definitely something wrong here still as the power steps in the [power zip example](https://github.com/stadelmanma/fitparse-rs/files/9951761/power_activity_fit.zip) I provided, get parsed to `custom_target_value_low/high` as shown in original issue comment, but the heart rate version in the [failing hr fit example](https://github.com/stadelmanma/fitparse-rs/files/9938819/failing_activity.zip) is left as original. 
  https://www.fitfileviewer.com/ parses both to the standard `custom_target_value_low/high`, the python lib seems to leave both as original. So there are two options but it seems definitely one needs sticking too, rather than current variable behaviour, i'd prefer the former option (standard naming). 

Let me know if there's anything else you think it might help if I test!

![image](https://user-images.githubusercontent.com/44890343/204871720-49f3f0a0-0f95-4112-88eb-5c77e5520175.png)
![image](https://user-images.githubusercontent.com/44890343/204871809-cb5a7d62-8135-48ef-8959-0d17c8e50c88.png)
![image](https://user-images.githubusercontent.com/44890343/204871965-3b9848b1-0e52-4943-bc84-61edc02368bc.png)
![image](https://user-images.githubusercontent.com/44890343/204872058-96a77680-e789-4e28-8d47-47143998bd1a.png)
![image](https://user-images.githubusercontent.com/44890343/204872245-8f0c0caa-7752-450d-a25d-d8be3b2f86f8.png)

**Comment by stadelmanma** [comment]
Did some more digging, into the values in the power fit file. I think I know what's happening but I don't think there is a clean fix that might not end up being fragile. The enum used to check the target type subfield is defined as such:
```
impl WktStepTarget {
    pub fn as_u8(self) -> u8 {
        match self {
            WktStepTarget::Speed => 0,
            WktStepTarget::HeartRate => 1,
            WktStepTarget::Open => 2,
            WktStepTarget::Cadence => 3,
            WktStepTarget::Power => 4,
            WktStepTarget::Grade => 5,
            WktStepTarget::Resistance => 6,
            WktStepTarget::Power3s => 7,
            WktStepTarget::Power10s => 8,
            WktStepTarget::Power30s => 9,
            WktStepTarget::PowerLap => 10,
            WktStepTarget::SwimStroke => 11,
            WktStepTarget::SpeedLap => 12,
            WktStepTarget::HeartRateLap => 13,
            WktStepTarget::UnknownVariant(value) => value,
        }
    }
```
The way subfields are defined in the profile is show below:
![custom-target-subflds](https://user-images.githubusercontent.com/16710141/205801494-cb473fc3-4ea5-45fc-b989-63ec4dcb7f4d.png)

As things stand  only the first 4 values can resolve to a subfield to get the additional info provided. The file you provided sets the target type to `WktStepTarget::Power3s` which doesn't get covered since we only get a subfield definition in the profile for regular "Power".

So what is happening as the code stands isn't a bug but expected behavior. That being said I don't think I'm immediately opposed to leaving the name as the "Generic" version but pulling units and scale/offset semantics from the subfield if it's available. I'll need to look through what subfields get defined a little more closely.

**Comment by zakstucke** [comment]
@stadelmanma checked out the `DecodeOption::ReturnNumericEnumValues` option, it works but returns numbers for every field, rather than just the ones which were previously unknown. Another option to only do this for unknown field/value types would cover all cases. 

Your comments about the discrepant handling of the field naming (WktStepTarget::Power3s) makes sense. As with the similar trend of this thread, I'd say making fewer decisions and providing the information to the user to use as they see fit makes the most sense. 

So to sum up all the changes I think we've reached: 

- `DecodeOption::ReturnNumericEnumValues` (implemented) as an option to only output raw numeric values.
- `DecodeOption::ReturnNumericEnumValuesForUnknownOnly` (new), to return integers for fields which could not be identified only.
-  `DecodeOption::GenericNamingOnly` (new) to name fields generically only, and add their sub types (if exist) to the `FitDataField` outputted.

I think these options would provide much greater flexibility to the end user. 
If these are satisfied, I think it covers all the issues uncovered, what do you think?

**Comment by alexlatif** [comment]
@stadelmanma this is also a blocker for me parsing the same Garmin fit files. would be grateful if you could help fix this

**Comment by stadelmanma** [comment]
@alexlatif sorry I haven't had the time to try and address the good ideas mentioned in the last comment, although `DecodeOption::GenericNamingOnly` one has more difficulty baked in than it would seem since we auto generate the code used to decode raw data based on a profile.

**Comment by zakstucke** [comment]
Sounds great @stadelmanma!

**Comment by stadelmanma** [comment]
@zakstucke  and @alexlatif sorry that this has been such a long time coming, #23 will be the branch these features land on which has the new functional decoding logic implemented.
